# Generated by Django 4.0.2 on 2022-04-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedjob',
            name='salary',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
